### ISSUE TITLE
Release branch indicated in ReadMe does not exist

### ISSUE THREAD

**Issue by JeanFred** [sourcegraph/phabricator-extension#9]
The ReadMe advises to clone the `release-v1.0` branch
```
git clone -b release-v1.0 https://github.com/sourcegraph/phabricator-extension.git phabricator/src/extensions/sourcegraph
```

but this branch does not exist in the upstream.

Reproduction steps:
```
$ git clone -b release-v1.0 https://github.com/sourcegraph/phabricator-extension.git phabricator/src/extensions/sourcegraph
Cloning into 'phabricator/src/extensions/sourcegraph'...
fatal: Remote branch release-v1.0 not found in upstream origin
```

**Comment by KattMingMing** [comment]
@JeanFred - The release branch has been pushed upstream. If you are running Sourcegraph Server via docker you will need to use `sourcegraph/server:insiders`. Let us know if you run into any issues. Thanks for reporting 👍

**Comment by JeanFred** [comment]
Thanks for the quick fix @KattMingMing!
(Unfortunately, I don’t administer a Phabricator instance anymore, but I’m still interested to see where the Sourcegraph integration is going :)
